#!/usr/bin/env bash
# Configures Nginx for 301 redirection

# Install nginx if not installed
apt-get update
apt-get install -y nginx

# Create index page
echo "Hello World!" > /var/www/html/index.html

# Configure redirection
CONFIG_PATH="/etc/nginx/sites-available/default"
REDIRECT_CONFIG="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "/server_name _;/a\\$REDIRECT_CONFIG" "$CONFIG_PATH"

# Restart nginx (without systemctl)
/etc/init.d/nginx restart