#!/usr/bin/env bash
# Configures Nginx with custom 404 page

# Install nginx if not installed
apt-get update
apt-get install -y nginx

# Create index and 404 pages
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure custom 404 page
CONFIG_PATH="/etc/nginx/sites-available/default"
ERROR_CONFIG="\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sed -i "/server_name _;/a\\$ERROR_CONFIG" "$CONFIG_PATH"

# Restart nginx (without systemctl)
/etc/init.d/nginx restart