#!/usr/bin/env bash
# Installs and configures HAProxy on a new Ubuntu machine

# Install HAProxy
apt-get update
apt-get install -y haproxy

# Enable HAProxy to be started by init script
echo "ENABLED=1" >> /etc/default/haproxy

# Create HAProxy configuration
cat > /etc/haproxy/haproxy.cfg << EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 54.234.41.125:80 check
    server web-02 STUDENT_ID-web-02:80 check
EOF

# Start HAProxy (without systemctl)
/etc/init.d/haproxy start