#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 in 5 lines or less

service nginx stop
rm -f /etc/nginx/sites-enabled/default
echo "server { listen 80 default_server; listen [::]:80 default_server; root /var/www/html; index index.html index.htm; server_name _; location / { try_files \$uri \$uri/ =404; } }" > /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx start