#!/usr/bin/env bash
# This script displays the content of the current directory in list format
for file in *
do
    if [ "${file:0:1}" != "." ]
    then
        echo "$file" | cut -d'-' -f2-
    fi
done