#!/bin/bash
# Install ufw
sudo apt-get update
sudo apt-get install ufw -y

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow specific ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable ufw
sudo ufw enable

# Check ufw status
sudo ufw status verbose